name: Test CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: centos7
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: 
          cd /home/rfp
          git pull
